<template>
  <section>
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-2xl font-black">Categorías</h2><p class="text-sm text-slate-500">Organiza los productos visibles en Flutter y la web.</p></div><button class="btn btn-primary" @click="nueva">+ Nueva categoría</button></div>
    <p v-if="mensaje" :class="esError?'alert-error':'alert-success'" class="mb-4">{{ mensaje }}</p>
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><article v-for="c in categorias" :key="c.id" class="card p-5"><div class="flex items-start justify-between gap-3"><div><span class="badge badge-blue">{{ c.productos||0 }} productos</span><h3 class="mt-3 text-lg font-black">{{ c.nombre }}</h3></div><div class="flex gap-2"><button class="btn btn-secondary btn-sm" @click="editar(c)">Editar</button><button class="btn btn-danger btn-sm" @click="eliminar(c)">Eliminar</button></div></div><p class="mt-3 text-sm leading-6 text-slate-500">{{ c.descripcion }}</p></article></div><div v-if="!categorias.length" class="card p-10 text-center text-slate-500">No hay categorías.</div>
    <div v-if="modal" class="modal-backdrop" @click.self="modal=false"><section class="modal max-w-lg"><header class="flex justify-between border-b p-5"><h3 class="text-xl font-black">{{ editando?'Editar categoría':'Nueva categoría' }}</h3><button class="btn btn-secondary btn-sm" @click="modal=false">Cerrar</button></header><form class="space-y-4 p-5" @submit.prevent="guardar"><div><label class="label">Nombre</label><input v-model.trim="form.nombre" class="input" required /></div><div><label class="label">Descripción</label><textarea v-model.trim="form.descripcion" class="input" rows="4" required /></div><p v-if="errorForm" class="alert-error">{{ errorForm }}</p><div class="flex justify-end gap-3"><button type="button" class="btn btn-secondary" @click="modal=false">Cancelar</button><button class="btn btn-primary">Guardar</button></div></form></section></div>
  </section>
</template>
<script setup>
import{onMounted,reactive,ref}from'vue';import categoriaService from'../services/categoriaService.js';const categorias=ref([]),modal=ref(false),editando=ref(null),mensaje=ref(''),esError=ref(false),errorForm=ref('');const form=reactive({nombre:'',descripcion:''});async function cargar(){try{categorias.value=await categoriaService.obtenerCategorias();}catch(e){mensaje.value=e.response?.data?.mensaje||'No se pudo cargar';esError.value=true;}}function nueva(){editando.value=null;Object.assign(form,{nombre:'',descripcion:''});errorForm.value='';modal.value=true;}function editar(c){editando.value=c;Object.assign(form,{nombre:c.nombre,descripcion:c.descripcion});errorForm.value='';modal.value=true;}async function guardar(){try{if(editando.value)await categoriaService.actualizarCategoria(editando.value.id,form);else await categoriaService.crearCategoria(form);modal.value=false;mensaje.value=editando.value?'Categoría actualizada':'Categoría creada';esError.value=false;await cargar();}catch(e){errorForm.value=e.response?.data?.mensaje||'No se pudo guardar';}}async function eliminar(c){if(!confirm(`¿Eliminar ${c.nombre}?`))return;try{await categoriaService.eliminarCategoria(c.id);mensaje.value='Categoría eliminada';esError.value=false;await cargar();}catch(e){mensaje.value=e.response?.data?.mensaje||'No se puede eliminar; probablemente tiene productos relacionados';esError.value=true;}}onMounted(cargar);
</script>
