<template>
  <section>
    <div class="mb-6"><h1 class="text-2xl font-black">Conversaciones</h1><p class="text-sm text-slate-500">Tus mensajes se comparten con la aplicación móvil.</p></div>
    <p v-if="error" class="alert-error mb-4">{{ error }}</p>
    <div class="card grid min-h-[620px] overflow-hidden lg:grid-cols-[340px_1fr]">
      <aside class="border-b border-slate-200 lg:border-b-0 lg:border-r"><div class="border-b p-4"><button class="btn btn-secondary w-full" @click="cargarConversaciones">Actualizar conversaciones</button></div><div class="max-h-[560px] overflow-y-auto"><button v-for="c in conversaciones" :key="c.id" class="block w-full border-b p-4 text-left hover:bg-slate-50" :class="seleccionada?.id===c.id?'bg-blue-50':''" @click="seleccionar(c)"><div class="flex justify-between gap-2"><strong class="text-sm">{{ c.otro_usuario }}</strong><span v-if="c.mensajes_no_leidos" class="badge badge-blue">{{ c.mensajes_no_leidos }}</span></div><p class="mt-1 text-xs font-bold text-blue-700">{{ c.producto }}</p><p class="mt-1 truncate text-xs text-slate-500">{{ c.tipo_ultimo_mensaje==='imagen'?'Imagen':c.ultimo_mensaje||'Sin mensajes' }}</p></button><div v-if="!conversaciones.length" class="p-8 text-center text-sm text-slate-500">No tienes conversaciones.</div></div></aside>
      <div v-if="seleccionada" class="flex min-h-[500px] flex-col"><header class="border-b p-4"><strong>{{ seleccionada.otro_usuario }}</strong><p class="text-xs text-slate-500">Producto: {{ seleccionada.producto }}</p></header><div ref="mensajesCaja" class="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-4"><div v-for="m in mensajes" :key="m.id" class="flex" :class="Number(m.emisor_id)===Number(usuario.id)?'justify-end':'justify-start'"><div class="max-w-[80%] rounded-2xl px-4 py-3 text-sm shadow-sm" :class="Number(m.emisor_id)===Number(usuario.id)?'bg-blue-600 text-white':'bg-white text-slate-700'"><p v-if="m.tipo!=='imagen'">{{ m.mensaje }}</p><img v-else :src="apiAsset(m.imagen)" class="max-h-72 rounded-xl" /><span class="mt-1 block text-[10px] opacity-70">{{ fecha(m.fecha) }}</span></div></div><p v-if="!mensajes.length" class="pt-20 text-center text-sm text-slate-500">Inicia la conversación.</p></div><form class="flex flex-wrap gap-2 border-t bg-white p-4" @submit.prevent="enviar"><input v-model.trim="texto" class="input min-w-48 flex-1" placeholder="Escribe un mensaje..." /><label class="btn btn-secondary">Imagen<input class="hidden" type="file" accept="image/jpeg,image/png,image/webp" @change="enviarArchivo" /></label><button class="btn btn-primary" :disabled="!texto||enviando">Enviar</button></form></div>
      <div v-else class="grid min-h-[500px] place-items-center p-8 text-center text-slate-500">Selecciona una conversación.</div>
    </div>
  </section>
</template>
<script setup>
import{nextTick,onMounted,ref}from'vue';import{useRoute}from'vue-router';import authService from'../services/authService.js';import chatService from'../services/chatService.js';import{apiAsset}from'../services/api.js';
const route=useRoute(),usuario=authService.obtenerUsuario();const conversaciones=ref([]),seleccionada=ref(null),mensajes=ref([]),texto=ref(''),enviando=ref(false),error=ref(''),mensajesCaja=ref(null);
function fecha(v){return v?new Date(v).toLocaleString('es-PE'):'';}async function scroll(){await nextTick();if(mensajesCaja.value)mensajesCaja.value.scrollTop=mensajesCaja.value.scrollHeight;}
async function cargarConversaciones(){try{conversaciones.value=await chatService.conversaciones(usuario.id);const id=Number(route.query.id);if(id){const c=conversaciones.value.find(x=>Number(x.id)===id);if(c)await seleccionar(c);}}catch(e){error.value=e.response?.data?.mensaje||'No se pudieron cargar las conversaciones';}}
async function seleccionar(c){seleccionada.value=c;try{mensajes.value=await chatService.mensajes(c.id);await chatService.marcarLeidos(c.id,usuario.id);await scroll();}catch(e){error.value=e.response?.data?.mensaje||'No se pudieron cargar los mensajes';}}
async function enviar(){if(!texto.value)return;enviando.value=true;try{await chatService.enviar(seleccionada.value.id,usuario.id,texto.value);texto.value='';mensajes.value=await chatService.mensajes(seleccionada.value.id);await scroll();}catch(e){error.value=e.response?.data?.mensaje||'No se pudo enviar';}finally{enviando.value=false;}}
async function enviarArchivo(event){const archivo=event.target.files?.[0];if(!archivo||!seleccionada.value)return;enviando.value=true;try{await chatService.enviarImagen(seleccionada.value.id,usuario.id,archivo);mensajes.value=await chatService.mensajes(seleccionada.value.id);await scroll();}catch(e){error.value=e.response?.data?.mensaje||'No se pudo enviar la imagen';}finally{event.target.value='';enviando.value=false;}}
onMounted(cargarConversaciones);
</script>
