<template>
  <section class="mx-auto max-w-3xl">
    <div class="mb-6"><h1 class="text-2xl font-black">Mi perfil</h1><p class="text-sm text-slate-500">Edita los mismos datos que utilizas en Flutter.</p></div>
    <div class="card p-6"><form class="grid gap-4 sm:grid-cols-2" @submit.prevent="guardar"><div class="sm:col-span-2"><label class="label">Nombre</label><input v-model.trim="form.nombre" class="input" required /></div><div class="sm:col-span-2"><label class="label">Correo</label><input v-model.trim="form.correo" class="input" type="email" required /></div><div><label class="label">Teléfono</label><input v-model.trim="form.telefono" class="input" /></div><div><label class="label">Ubicación</label><input v-model.trim="form.ubicacion" class="input" /></div><div class="sm:col-span-2"><label class="label">URL de foto de perfil</label><input v-model.trim="form.imagen_perfil" class="input" /></div><p v-if="mensaje" :class="error?'alert-error':'alert-success'" class="sm:col-span-2">{{ mensaje }}</p><div class="sm:col-span-2"><button class="btn btn-primary" :disabled="guardando">Guardar perfil</button></div></form></div>
    <div class="card mt-6 p-6"><h2 class="text-lg font-black">Cambiar contraseña</h2><form class="mt-4 grid gap-4 sm:grid-cols-2" @submit.prevent="cambiar"><div><label class="label">Contraseña actual</label><input v-model="password.actual" class="input" type="password" required /></div><div><label class="label">Nueva contraseña</label><input v-model="password.nueva" class="input" type="password" minlength="6" required /></div><p v-if="mensajePassword" :class="errorPassword?'alert-error':'alert-success'" class="sm:col-span-2">{{ mensajePassword }}</p><div class="sm:col-span-2"><button class="btn btn-secondary">Actualizar contraseña</button></div></form></div>
  </section>
</template>
<script setup>
import{onMounted,reactive,ref}from'vue';import authService from'../services/authService.js';import usuarioService from'../services/usuarioService.js';const usuario=authService.obtenerUsuario();const form=reactive({nombre:'',correo:'',telefono:'',ubicacion:'',imagen_perfil:''});const password=reactive({actual:'',nueva:''});const mensaje=ref(''),error=ref(false),guardando=ref(false),mensajePassword=ref(''),errorPassword=ref(false);
onMounted(async()=>{const p=await usuarioService.obtenerPerfil(usuario.id);Object.assign(form,p);});async function guardar(){guardando.value=true;try{await usuarioService.actualizarPerfil(usuario.id,form);authService.guardarUsuario({...usuario,...form});mensaje.value='Perfil actualizado';error.value=false;}catch(e){mensaje.value=e.response?.data?.mensaje||'No se pudo actualizar';error.value=true;}finally{guardando.value=false;}}
async function cambiar(){try{await usuarioService.cambiarPassword(usuario.id,{passwordActual:password.actual,passwordNueva:password.nueva});mensajePassword.value='Contraseña actualizada';errorPassword.value=false;password.actual='';password.nueva='';}catch(e){mensajePassword.value=e.response?.data?.mensaje||'No se pudo actualizar';errorPassword.value=true;}}
</script>
