<template>
  <section>
    <div class="mb-6"><h2 class="text-2xl font-black">Productos publicados</h2><p class="text-sm text-slate-500">Administradores y superadministradores pueden corregir o eliminar cualquier publicación.</p></div>
    <div class="mb-4 grid gap-3 md:grid-cols-[1fr_auto]"><input v-model.trim="busqueda" class="input" placeholder="Buscar producto o vendedor..." /><button class="btn btn-secondary" @click="cargar">Actualizar</button></div>
    <p v-if="mensaje" :class="esError?'alert-error':'alert-success'" class="mb-4">{{ mensaje }}</p>
    <div class="card table-wrap"><table class="table"><thead><tr><th>Producto</th><th>Vendedor</th><th>Precio/stock</th><th>Categoría</th><th>Acciones</th></tr></thead><tbody><tr v-for="p in filtrados" :key="p.id"><td><div class="flex min-w-64 items-center gap-3"><img v-if="p.imagen" :src="apiAsset(p.imagen)" class="h-14 w-16 rounded-lg object-cover" /><div class="h-14 w-16 rounded-lg bg-slate-200" v-else></div><div><strong class="block">{{ p.nombre }}</strong><span class="line-clamp-1 text-xs text-slate-500">{{ p.descripcion }}</span></div></div></td><td>{{ p.vendedor }}</td><td><strong>S/ {{ Number(p.precio).toFixed(2) }}</strong><span class="block text-xs text-slate-500">Stock: {{ p.stock }}</span></td><td>{{ p.categoria_nombre||'—' }}</td><td><div class="flex gap-2"><button class="btn btn-secondary btn-sm" @click="editar(p)">Editar</button><button class="btn btn-danger btn-sm" @click="eliminar(p)">Eliminar</button></div></td></tr></tbody></table><div v-if="!filtrados.length" class="p-8 text-center text-slate-500">No hay productos.</div></div>
    <div v-if="modal" class="modal-backdrop" @click.self="modal=false"><section class="modal"><header class="flex justify-between border-b p-5"><div><h3 class="text-xl font-black">Editar producto</h3><p class="text-sm text-slate-500">Modificación administrativa.</p></div><button class="btn btn-secondary btn-sm" @click="modal=false">Cerrar</button></header><form class="grid gap-4 p-5 sm:grid-cols-2" @submit.prevent="guardar"><div class="sm:col-span-2"><label class="label">Nombre</label><input v-model.trim="form.nombre" class="input" required /></div><div class="sm:col-span-2"><label class="label">Descripción</label><textarea v-model.trim="form.descripcion" class="input" rows="4" required /></div><div><label class="label">Precio</label><input v-model="form.precio" class="input" type="number" step=".01" min=".01" required /></div><div><label class="label">Stock</label><input v-model="form.stock" class="input" type="number" min="0" required /></div><div><label class="label">Categoría</label><select v-model="form.categoria_id" class="input" required><option v-for="c in categorias" :key="c.id" :value="c.id">{{ c.nombre }}</option></select></div><div><label class="label">Ubicación</label><input v-model.trim="form.ubicacion" class="input" required /></div><div class="sm:col-span-2"><label class="label">Reemplazar imagen</label><input class="input" type="file" accept="image/*" @change="imagen=$event.target.files?.[0]||null" /></div><p v-if="errorForm" class="alert-error sm:col-span-2">{{ errorForm }}</p><div class="flex justify-end gap-3 sm:col-span-2"><button type="button" class="btn btn-secondary" @click="modal=false">Cancelar</button><button class="btn btn-primary">Guardar</button></div></form></section></div>
  </section>
</template>
<script setup>
import{computed,onMounted,reactive,ref}from'vue';import productoService from'../services/productoService.js';import categoriaService from'../services/categoriaService.js';import{apiAsset}from'../services/api.js';const productos=ref([]),categorias=ref([]),busqueda=ref(''),modal=ref(false),editando=ref(null),imagen=ref(null),mensaje=ref(''),esError=ref(false),errorForm=ref('');const form=reactive({nombre:'',descripcion:'',precio:'',stock:'',categoria_id:'',ubicacion:''});const filtrados=computed(()=>{const q=busqueda.value.toLowerCase();return productos.value.filter(p=>!q||[p.nombre,p.vendedor,p.ubicacion].some(v=>String(v||'').toLowerCase().includes(q)));});async function cargar(){try{[productos.value,categorias.value]=await Promise.all([productoService.obtenerProductos(),categoriaService.obtenerCategorias()]);}catch(e){mensaje.value=e.response?.data?.mensaje||'No se pudo cargar';esError.value=true;}}function editar(p){editando.value=p;imagen.value=null;errorForm.value='';Object.assign(form,{nombre:p.nombre,descripcion:p.descripcion,precio:p.precio,stock:p.stock,categoria_id:p.categoria_id,ubicacion:p.ubicacion});modal.value=true;}function fd(){const x=new FormData();Object.entries(form).forEach(([k,v])=>x.append(k,v));if(imagen.value)x.append('imagen',imagen.value);return x;}async function guardar(){try{await productoService.actualizarProductoAdmin(editando.value.id,fd());modal.value=false;mensaje.value='Producto actualizado';esError.value=false;await cargar();}catch(e){errorForm.value=e.response?.data?.mensaje||'No se pudo guardar';}}async function eliminar(p){if(!confirm(`¿Eliminar ${p.nombre}?`))return;try{await productoService.eliminarProductoAdmin(p.id);mensaje.value='Producto eliminado';esError.value=false;await cargar();}catch(e){mensaje.value=e.response?.data?.mensaje||'No se pudo eliminar';esError.value=true;}}onMounted(cargar);
</script>
