<template>
  <section>
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-2xl font-black">Gestión de usuarios</h2><p class="text-sm text-slate-500">El superadministrador puede cambiar roles, estados y permisos.</p></div><button class="btn btn-primary" @click="nuevo">+ Nuevo usuario</button></div>
    <p v-if="mensaje" :class="esError?'alert-error':'alert-success'" class="mb-4">{{ mensaje }}</p>
    <div class="card table-wrap"><table class="table"><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th><th>Contacto</th><th>Acciones</th></tr></thead><tbody><tr v-for="u in usuarios" :key="u.id"><td><strong class="block">{{ u.nombre }}</strong><span class="text-xs text-slate-500">{{ u.correo }}</span></td><td><span class="badge" :class="u.rol==='superadministrador'?'badge-amber':u.rol==='administrador'?'badge-blue':'badge-green'">{{ u.rol }}</span></td><td><span class="badge" :class="Number(u.activo)===1&&u.estado==='activo'?'badge-green':'badge-red'">{{ u.estado }}</span></td><td><span class="block text-sm">{{ u.telefono||'—' }}</span><span class="text-xs text-slate-500">{{ u.ubicacion||'—' }}</span></td><td><div class="flex gap-2"><button class="btn btn-secondary btn-sm" @click="editar(u)">Editar</button><button class="btn btn-danger btn-sm" :disabled="u.id===actual.id" @click="eliminar(u)">Desactivar</button></div></td></tr></tbody></table><div v-if="!usuarios.length" class="p-8 text-center text-slate-500">No hay usuarios.</div></div>

    <div v-if="modal" class="modal-backdrop" @click.self="cerrar"><section class="modal"><header class="flex items-center justify-between border-b p-5"><div><h3 class="text-xl font-black">{{ editando?'Editar usuario':'Crear usuario' }}</h3><p class="text-sm text-slate-500">{{ esSuper?'Control total habilitado':'Los administradores solo gestionan usuarios normales.' }}</p></div><button class="btn btn-secondary btn-sm" @click="cerrar">Cerrar</button></header><form class="grid gap-4 p-5 sm:grid-cols-2" @submit.prevent="guardar"><div><label class="label">Nombre</label><input v-model.trim="form.nombre" class="input" required /></div><div><label class="label">Correo</label><input v-model.trim="form.correo" class="input" type="email" required /></div><div><label class="label">Teléfono</label><input v-model.trim="form.telefono" class="input" /></div><div><label class="label">Ubicación</label><input v-model.trim="form.ubicacion" class="input" /></div><div><label class="label">Rol</label><select v-model="form.rol" class="input" :disabled="!esSuper"><option value="usuario">Usuario</option><option value="administrador">Administrador</option><option value="superadministrador">Superadministrador</option></select></div><div><label class="label">Estado</label><select v-model="form.estado" class="input"><option value="activo">Activo</option><option value="inactivo">Inactivo</option><option value="bloqueado">Bloqueado</option><option value="eliminado">Eliminado</option></select></div><div><label class="label">Acceso</label><select v-model.number="form.activo" class="input"><option :value="1">Habilitado</option><option :value="0">Deshabilitado</option></select></div><div v-if="!editando"><label class="label">Contraseña inicial</label><input v-model="form.password" class="input" type="password" minlength="6" required /></div><p v-if="errorForm" class="alert-error sm:col-span-2">{{ errorForm }}</p><div class="flex justify-end gap-3 sm:col-span-2"><button type="button" class="btn btn-secondary" @click="cerrar">Cancelar</button><button class="btn btn-primary" :disabled="guardando">{{ guardando?'Guardando...':'Guardar' }}</button></div></form></section></div>
  </section>
</template>
<script setup>
import{computed,onMounted,reactive,ref}from'vue';import authService from'../services/authService.js';import usuarioService from'../services/usuarioService.js';const actual=authService.obtenerUsuario();const esSuper=computed(()=>actual.rol==='superadministrador');const usuarios=ref([]),modal=ref(false),editando=ref(null),guardando=ref(false),mensaje=ref(''),esError=ref(false),errorForm=ref('');const form=reactive({nombre:'',correo:'',telefono:'',ubicacion:'',rol:'usuario',estado:'activo',activo:1,password:''});
function reset(){Object.assign(form,{nombre:'',correo:'',telefono:'',ubicacion:'',rol:'usuario',estado:'activo',activo:1,password:''});errorForm.value='';}async function cargar(){try{usuarios.value=await usuarioService.obtenerUsuarios();}catch(e){mensaje.value=e.response?.data?.mensaje||'No se pudieron cargar';esError.value=true;}}
function nuevo(){reset();editando.value=null;modal.value=true;}function editar(u){reset();editando.value=u;Object.assign(form,{nombre:u.nombre,correo:u.correo,telefono:u.telefono||'',ubicacion:u.ubicacion||'',rol:u.rol,estado:u.estado,activo:Number(u.activo)});modal.value=true;}function cerrar(){modal.value=false;}
async function guardar(){guardando.value=true;errorForm.value='';try{if(editando.value)await usuarioService.actualizarUsuario(editando.value.id,form);else await usuarioService.crearUsuario(form);modal.value=false;mensaje.value=editando.value?'Usuario actualizado':'Usuario creado';esError.value=false;await cargar();}catch(e){errorForm.value=e.response?.data?.mensaje||'No se pudo guardar';}finally{guardando.value=false;}}
async function eliminar(u){if(!confirm(`¿Desactivar a ${u.nombre}?`))return;try{await usuarioService.eliminarUsuario(u.id);mensaje.value='Usuario desactivado';esError.value=false;await cargar();}catch(e){mensaje.value=e.response?.data?.mensaje||'No se pudo desactivar';esError.value=true;}}
onMounted(cargar);
</script>
